### ISSUE TITLE
Question about the dataset of this project.

### ISSUE THREAD

**Issue by zixufang** [AIJoris/DP-DialogueGAN#1]
Hi,I am so happy to find this project.
But I am confused about the dataset.
May I ask where the dataset come from? And is it a public dataset?
I find no other way to contact you, so I can only use this way to seek your help.

**Comment by jsbaan** [comment]
Hi zixufang,

I'm glad this project is useful to you. We used the Daily Dialogue dataset (yanran2017dailydialog). Please bear in mind that this work is no longer actively updated nor fully tested!

**Comment by zixufang** [comment]
thank you.
So, you put up a new model called "DPAC".  You didn't write a paper about your model?
I didn't find relevant paper about it .

**Comment by jsbaan** [comment]
We did, I will add it to the project. We never sent it to any conference, it was just for the project evaluation for the University of Amsterdam.

**Comment by zixufang** [comment]
May I ask ，which discriminator have you tested? The "discriminator.py" or "discriminator_LM.py" or "discriminator_LM2.py"?
I came across model collapse when I was training with SEQGAN.It has disturbed me for a few days.
I would appreciate it if you can give me the info!!

**Comment by jsbaan** [comment]
I think we tested discriminator.py (binary discriminator) and discriminator_LM2.py (language model based discriminator). If I recall correctly, LM1 was replaced by LM2 because we had problems with the implementation.
